version: '3.8'

services:
  app:
    image: jhanmarcogodoylevano/demo_t07_nexcoin:6cab911a
    ports:
      - "8080:80"  # Mapea el puerto 80 del contenedor al 8080 de tu máquina local o servidor
    environment:
      - NODE_ENV=vallegrande  # Configuración del entorno de producción
      - API_TIMEOUT=5000     # Ejemplo de timeout para las solicitudes a APIs externas (ajusta según tu app)
    deploy:
      replicas: 2           # Configura el número de réplicas (útil en despliegues en producción)
      resources:
        limits:
          cpus: '0.5'       # Limita el uso de CPU para optimizar recursos
          memory: 512M      # Limita el uso de memoria
      restart_policy:
        condition: on-failure  # Reinicia solo si falla
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
