name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
      - ejemplo01/JhanmarcoGodoy
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install

      - run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/  # Asegúrate de que esta carpeta exista

  sonarcloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code and Download Build Artifact
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: build-output  # Asegúrate de que el nombre coincida

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_JHANMARCO }}
