name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
      - ejemplo01/JhanmarcoGodoy
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install

      - run: npm run build  # Ejecuta el build del proyecto

  sonarcloud:
    needs: build  # Este job depende de la ejecución del job `build` 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Asegúrate de obtener todo el historial del repositorio

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_JHANMARCO }}
